"""empty message

Revision ID: 467d009fb94
Revises: 4b672120c85
Create Date: 2015-10-20 20:58:14.149376

"""

# revision identifiers, used by Alembic.
revision = '467d009fb94'
down_revision = '4b672120c85'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('champion', sa.Column('blurb', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('champion', 'blurb')
    ### end Alembic commands ###
