"""empty message

Revision ID: 4b672120c85
Revises: None
Create Date: 2015-10-20 20:12:52.544314

"""

# revision identifiers, used by Alembic.
revision = '4b672120c85'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('champion',
    sa.Column('champ_name', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('attack', sa.Integer(), nullable=True),
    sa.Column('defense', sa.Integer(), nullable=True),
    sa.Column('magic', sa.Integer(), nullable=True),
    sa.Column('key', sa.Integer(), nullable=True),
    sa.Column('lore', sa.String(), nullable=True),
    sa.Column('partype', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('champ_name')
    )
    op.create_table('ability',
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('costType', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('maxrank', sa.Integer(), nullable=True),
    sa.Column('spell_name', sa.String(), nullable=True),
    sa.Column('champ_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['champ_name'], ['champion.champ_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('champion_info',
    sa.Column('attack', sa.Integer(), nullable=True),
    sa.Column('defense', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('magic', sa.Integer(), nullable=True),
    sa.Column('champ_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['champ_name'], ['champion.champ_name'], ),
    sa.PrimaryKeyConstraint('champ_name')
    )
    op.create_table('champion_passive',
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('passive_name', sa.String(), nullable=False),
    sa.Column('champ_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['champ_name'], ['champion.champ_name'], ),
    sa.PrimaryKeyConstraint('passive_name')
    )
    op.create_table('champion_skin',
    sa.Column('chromas', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('skin_name', sa.String(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.Column('champ_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['champ_name'], ['champion.champ_name'], ),
    sa.PrimaryKeyConstraint('skin_name')
    )
    op.create_table('champion_stat',
    sa.Column('armor', sa.Float(), nullable=True),
    sa.Column('armorperlevel', sa.Float(), nullable=True),
    sa.Column('attacklevel', sa.Float(), nullable=True),
    sa.Column('attackdamageperlevel', sa.Float(), nullable=True),
    sa.Column('attackrange', sa.Float(), nullable=True),
    sa.Column('attackspeedoffset', sa.Float(), nullable=True),
    sa.Column('attackspeedperlevel', sa.Float(), nullable=True),
    sa.Column('crit', sa.Float(), nullable=True),
    sa.Column('critperlevel', sa.Float(), nullable=True),
    sa.Column('hp', sa.Float(), nullable=True),
    sa.Column('hpperlevel', sa.Float(), nullable=True),
    sa.Column('hpregen', sa.Float(), nullable=True),
    sa.Column('hpregenperlevel', sa.Float(), nullable=True),
    sa.Column('movespeed', sa.Float(), nullable=True),
    sa.Column('mp', sa.Float(), nullable=True),
    sa.Column('mpperlevel', sa.Float(), nullable=True),
    sa.Column('mpregen', sa.Float(), nullable=True),
    sa.Column('mpregenlevel', sa.Float(), nullable=True),
    sa.Column('spellblock', sa.Float(), nullable=True),
    sa.Column('spellblockperlevel', sa.Float(), nullable=True),
    sa.Column('champ_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['champ_name'], ['champion.champ_name'], ),
    sa.PrimaryKeyConstraint('champ_name')
    )
    op.create_table('champion_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(), nullable=True),
    sa.Column('champ_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['champ_name'], ['champion.champ_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('plaintext', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('champ_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['champ_name'], ['champion.champ_name'], ),
    sa.PrimaryKeyConstraint('item_name')
    )
    op.create_table('item_gold',
    sa.Column('model', sa.Integer(), nullable=True),
    sa.Column('purchaseable', sa.Boolean(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('sell', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['item_name'], ['item.item_name'], ),
    sa.PrimaryKeyConstraint('item_name')
    )
    op.create_table('item_stat',
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('stat_bonus', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['item_name'], ['item.item_name'], ),
    sa.PrimaryKeyConstraint('item_name')
    )
    op.create_table('item_tag',
    sa.Column('tag_name', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_name'], ['item.item_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_tag')
    op.drop_table('item_stat')
    op.drop_table('item_gold')
    op.drop_table('item')
    op.drop_table('champion_tag')
    op.drop_table('champion_stat')
    op.drop_table('champion_skin')
    op.drop_table('champion_passive')
    op.drop_table('champion_info')
    op.drop_table('ability')
    op.drop_table('champion')
    ### end Alembic commands ###
